### ISSUE TITLE
Latest and 3.8 versions are erroring out

### ISSUE THREAD

**Issue by tboerger** [nhedger/setup-sops#35]
Hi, I just wanted to start using this action but it results in failed builds for latest or 3.8.1 versions while 3.7.3 seem to work so far.

```
Run nhedger/setup-sops@v1
Error: Could not find a SOPS release for linux for the given version.
    at findAsset (file:///home/runner/work/_actions/nhedger/setup-sops/v1/dist/index.mjs:[13](https://github.com/promhippie/charts/actions/runs/6650826212/job/18071639599#step:5:14)344:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async download (file:///home/runner/work/_actions/nhedger/setup-sops/v1/dist/index.mjs:13284:22)
    at async setup (file:///home/runner/work/_actions/nhedger/setup-sops/v1/dist/index.mjs:13274:28)
    at async file:///home/runner/work/_actions/nhedger/setup-sops/v1/dist/index.mjs:13358:3
Error: Could not find a SOPS release for linux for the given version.
```

**Comment by tboerger** [comment]
Ok, just have seen there is a v2 of this action which does not have this issue, maybe you should update the docs for v2 :)

**Comment by nhedger** [comment]
Hey @tboerger, good catch. I'll update the docs; thanks for pointing it out.
